[package]
name = "cli-binscan"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "binscan"
path = "src/main.rs"

[dependencies]
library = { path = "../library" }
tokio = { version = "1", features = ["full"] }

# Command line parser
clap = { version = "4.0", features = ["derive"] } 

# CLI building Tools
indicatif = "0.17" 
owo-colors = "4"
comfy-table = "7" 
dialoguer = "0.11"